### ISSUE TITLE
Missing PenModuleServiceProvider

### ISSUE THREAD

**Issue by dotuancd** [vdhoangson/pen-test#1]
[Symfony\Component\Debug\Exception\FatalErrorException]

  Class 'PenFramework\Providers\PenModuleServiceProvider' not found

## Step to reproduce

```
laravel new blog
composer require vdhoangson/pen-test
# Add `PenFramework\Providers\PenFrameworkServiceProvider::class` to `config/app.php`

php artisan vendor:publish
```

**Comment by vdhoangson** [comment]
đã sửa lỗi trên. do mình có code phần module nhưng chưa hoàn thiện nên mình bỏ đi mà bỏ sót
bạn có thể clone lại hoặc sửa trong file vendor/pen-test/src/Providers/PenFrameworkServiceProvider.php bỏ dòng 43 `$this->app->register('PenFramework\Providers\PenModuleServiceProvider');`
